name: First Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
      - cron: "45 15 * * *"
env:
  PYTHON_VERSION: "3.14"

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Print DB Password
        run: echo "${{ secrets.DB_PASSWORD }}"
